Style/FrozenStringLiteralComment:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/NumericLiterals:
  Enabled: false

AllCops:
  Include:
    - '**/config.ru'
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'Rakefile'
    - 'lib/utils/*'
    - 'spec/**/*'
Documentation:
  Enabled: false
