# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8592480a4cd73b645719cb990ac02869e93c3deb481fc15758c7679277d24481c6d377150ccce984817566200562d45cf3781907dba9603f79f9245cd7dd7f6

test:
  secret_key_base: a696ffacf864a1b85645c19d4937c6b90f036f379822dd306f004b377bd2c0abe389f2751cf38235834d7849b00e3e06cde38d3782d3d98506a2d7872cd350db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
